package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ADS.
 */
public class Ads {

	private long aid;
	/** Not-null value. */
	private String icon;
	private int type;
	private String url;
	private Long media;
	private Integer category;
	private Integer article;

	public Ads() {
	}

	public Ads(long aid) {
		this.aid = aid;
	}

	public Ads(long aid, String icon, int type, String url, Long media,
			Integer category, Integer article) {
		this.aid = aid;
		this.icon = icon;
		this.type = type;
		this.url = url;
		this.media = media;
		this.category = category;
		this.article = article;
	}

	public long getAid() {
		return aid;
	}

	public void setAid(long aid) {
		this.aid = aid;
	}

	/** Not-null value. */
	public String getIcon() {
		return icon;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Long getMedia() {
		return media;
	}

	public void setMedia(Long media) {
		this.media = media;
	}

	public Integer getCategory() {
		return category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	public Integer getArticle() {
		return article;
	}

	public void setArticle(Integer article) {
		this.article = article;
	}

	@Override
	public boolean equals(Object o) {
		if (o instanceof Ads) {
			Ads t = (Ads) o;
			return this.aid == t.getAid();
		}
		return super.equals(o);
	}

}
