package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTICLE_CHAPTER_RECODE.
 */
public class ArticleChapterRecode {

    private long cpid=0;
    private long aid=0;
    private long cid=0;
    private String cpname;
    private Integer price;
    private Integer status;
    private java.util.Date dateline;

    public ArticleChapterRecode() {
    }

    public ArticleChapterRecode(long cpid) {
        this.cpid = cpid;
    }

    public ArticleChapterRecode(long cpid, Long aid, Long cid, String cpname, Integer price, Integer status, java.util.Date dateline) {
        this.cpid = cpid;
        this.aid = aid;
        this.cid = cid;
        this.cpname = cpname;
        this.price = price;
        this.status = status;
        this.dateline = dateline;
    }

    public long getCpid() {
        return cpid;
    }

    public void setCpid(long cpid) {
        this.cpid = cpid;
    }

    public long getAid() {
        return aid;
    }

    public void setAid(long aid) {
        this.aid = aid;
    }

    public long getCid() {
        return cid;
    }

    public void setCid(long cid) {
        this.cid = cid;
    }

    public String getCpname() {
        return cpname;
    }

    public void setCpname(String cpname) {
        this.cpname = cpname;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public java.util.Date getDateline() {
        return dateline;
    }

    public void setDateline(java.util.Date dateline) {
        this.dateline = dateline;
    }

}
