package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTICLE_FEEDBACK.
 */
public class ArticleFeedback {

    private long id;
    private long aid;
    private long userId;
    /** Not-null value. */
    private String icon;
    /** Not-null value. */
    private String nick;
    /** Not-null value. */
    private String account;
    /** Not-null value. */
    private String msg;
    private int stars;
    /** Not-null value. */
    private String dateline;

    public ArticleFeedback() {
    }

    public ArticleFeedback(long id) {
        this.id = id;
    }

    public ArticleFeedback(long id, long aid, long userId, String icon, String nick, String account, String msg, int stars, String dateline) {
        this.id = id;
        this.aid = aid;
        this.userId = userId;
        this.icon = icon;
        this.nick = nick;
        this.account = account;
        this.msg = msg;
        this.stars = stars;
        this.dateline = dateline;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getAid() {
        return aid;
    }

    public void setAid(long aid) {
        this.aid = aid;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getIcon() {
        return icon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /** Not-null value. */
    public String getNick() {
        return nick;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /** Not-null value. */
    public String getAccount() {
        return account;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccount(String account) {
        this.account = account;
    }

    /** Not-null value. */
    public String getMsg() {
        return msg;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    public int getStars() {
        return stars;
    }

    public void setStars(int stars) {
        this.stars = stars;
    }

    /** Not-null value. */
    public String getDateline() {
        return dateline;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateline(String dateline) {
        this.dateline = dateline;
    }
    @Override
   	public boolean equals(Object o) {
   		if (o instanceof ArticleFeedback) {
   			ArticleFeedback t = (ArticleFeedback) o;
   			return this.id == t.id;
   		}
   		return super.equals(o);
   	}
}
