package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTICLE_CHAPTER_INFO.
 */
public class ArticleChapterInfo {

    private long cpId;
    private long aid;
    /** Not-null value. */
    private String cpName;
    /** Not-null value. */
    private String cpIcon;
    /** Not-null value. */
    private String cpUrl;
    /** Not-null value. */
    private String cpDesc;
    private int cpSize;
    private float mCurrency;
    /** Not-null value. */
    private String Dateline;

    public ArticleChapterInfo() {
    }

    public ArticleChapterInfo(long cpId) {
        this.cpId = cpId;
    }

    public ArticleChapterInfo(long cpId, long aid, String cpName, String cpIcon, String cpUrl, String cpDesc, int cpSize, float mCurrency, String Dateline) {
        this.cpId = cpId;
        this.aid = aid;
        this.cpName = cpName;
        this.cpIcon = cpIcon;
        this.cpUrl = cpUrl;
        this.cpDesc = cpDesc;
        this.cpSize = cpSize;
        this.mCurrency = mCurrency;
        this.Dateline = Dateline;
    }

    public long getCpId() {
        return cpId;
    }

    public void setCpId(long cpId) {
        this.cpId = cpId;
    }

    public long getAid() {
        return aid;
    }

    public void setAid(long aid) {
        this.aid = aid;
    }

    /** Not-null value. */
    public String getCpName() {
        return cpName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCpName(String cpName) {
        this.cpName = cpName;
    }

    /** Not-null value. */
    public String getCpIcon() {
        return cpIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCpIcon(String cpIcon) {
        this.cpIcon = cpIcon;
    }

    /** Not-null value. */
    public String getCpUrl() {
        return cpUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCpUrl(String cpUrl) {
        this.cpUrl = cpUrl;
    }

    /** Not-null value. */
    public String getCpDesc() {
        return cpDesc;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCpDesc(String cpDesc) {
        this.cpDesc = cpDesc;
    }

    public int getCpSize() {
        return cpSize;
    }

    public void setCpSize(int cpSize) {
        this.cpSize = cpSize;
    }

    public float getMCurrency() {
        return mCurrency;
    }

    public void setMCurrency(float mCurrency) {
        this.mCurrency = mCurrency;
    }

    /** Not-null value. */
    public String getDateline() {
        return Dateline;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateline(String Dateline) {
        this.Dateline = Dateline;
    }
    @Override
	public boolean equals(Object o) {
		if (o instanceof ArticleChapterInfo) {
			ArticleChapterInfo t = (ArticleChapterInfo) o;
			return this.cpId == t.cpId;
		}
		return super.equals(o);
	}
}
