package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BASEUSER.
 */
public class Baseuser {

    private long uid;
    /** Not-null value. */
    private String nick;
    /** Not-null value. */
    private String account;
    /** Not-null value. */
    private String pwd;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private java.util.Date date;
    private String icon;
    private String sex;
    private String signature;
    private String contact;
    private String area;
    private String phone;
    private String email;

    public Baseuser() {
    }

    public Baseuser(long uid) {
        this.uid = uid;
    }

    public Baseuser(long uid, String nick, String account, String pwd, String type, java.util.Date date, String icon, String sex, String signature, String contact, String area, String phone, String email) {
        this.uid = uid;
        this.nick = nick;
        this.account = account;
        this.pwd = pwd;
        this.type = type;
        this.date = date;
        this.icon = icon;
        this.sex = sex;
        this.signature = signature;
        this.contact = contact;
        this.area = area;
        this.phone = phone;
        this.email = email;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    /** Not-null value. */
    public String getNick() {
        return nick;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /** Not-null value. */
    public String getAccount() {
        return account;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccount(String account) {
        this.account = account;
    }

    /** Not-null value. */
    public String getPwd() {
        return pwd;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    @Override
   	public boolean equals(Object o) {
   		if (o instanceof Baseuser) {
   			Baseuser t = (Baseuser) o;
   			return this.uid == t.uid;
   		}
   		return super.equals(o);
   	}
}
