package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY.
 */
public class Category {

	private long cId;
	/** Not-null value. */
	private String cIcon;
	/** Not-null value. */
	private String cName;
	/** Not-null value. */
	private String cDesc;
	private long media;
	private int cSort;

	public Category() {
	}

	public Category(long cId) {
		this.cId = cId;
	}

	public Category(long cId, String cIcon, String cName, String cDesc,
			long media, int cSort) {
		this.cId = cId;
		this.cIcon = cIcon;
		this.cName = cName;
		this.cDesc = cDesc;
		this.media = media;
		this.cSort = cSort;
	}

	public long getCId() {
		return cId;
	}

	public void setCId(long cId) {
		this.cId = cId;
	}

	/** Not-null value. */
	public String getCIcon() {
		return cIcon;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setCIcon(String cIcon) {
		this.cIcon = cIcon;
	}

	/** Not-null value. */
	public String getCName() {
		return cName;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setCName(String cName) {
		this.cName = cName;
	}

	/** Not-null value. */
	public String getCDesc() {
		return cDesc;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setCDesc(String cDesc) {
		this.cDesc = cDesc;
	}

	public long getMedia() {
		return media;
	}

	public void setMedia(long media) {
		this.media = media;
	}

	public int getCSort() {
		return cSort;
	}

	public void setCSort(int cSort) {
		this.cSort = cSort;
	}

	@Override
	public boolean equals(Object o) {
		if (o instanceof Category) {
			Category t = (Category) o;
			return this.cId == t.cId;
		}
		return super.equals(o);
	}

}
