package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_PEOPLE_INFO.
 */
public class ChatPeopleInfo {

    private long uid;
    private java.util.Date date;
    private Long interval_count;
    private String icon;
    private String nick;
    private String sex;
    private String signature;
    private String area;
    private Boolean isfriend;

    public ChatPeopleInfo() {
    }

    public ChatPeopleInfo(long uid) {
        this.uid = uid;
    }

    public ChatPeopleInfo(long uid, java.util.Date date, Long interval_count, String icon, String nick, String sex, String signature, String area, Boolean isfriend) {
        this.uid = uid;
        this.date = date;
        this.interval_count = interval_count;
        this.icon = icon;
        this.nick = nick;
        this.sex = sex;
        this.signature = signature;
        this.area = area;
        this.isfriend = isfriend;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Long getInterval_count() {
        return interval_count;
    }

    public void setInterval_count(Long interval_count) {
        this.interval_count = interval_count;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public Boolean getIsfriend() {
        return isfriend;
    }

    public void setIsfriend(Boolean isfriend) {
        this.isfriend = isfriend;
    }

}
