package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_MSG.
 */
public class ChatMsg {

    private Long id;
    private long Suid;
    private long Ruid;
    private String icon;
    private String name;
    private String msg;
    private long dateline;

    public ChatMsg() {
    }

    public ChatMsg(Long id) {
        this.id = id;
    }

    public ChatMsg(Long id, long Suid, long Ruid, String icon, String name, String msg, long dateline) {
        this.id = id;
        this.Suid = Suid;
        this.Ruid = Ruid;
        this.icon = icon;
        this.name = name;
        this.msg = msg;
        this.dateline = dateline;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getSuid() {
        return Suid;
    }

    public void setSuid(long Suid) {
        this.Suid = Suid;
    }

    public long getRuid() {
        return Ruid;
    }

    public void setRuid(long Ruid) {
        this.Ruid = Ruid;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public long getDateline() {
        return dateline;
    }

    public void setDateline(long dateline) {
        this.dateline = dateline;
    }
	@Override
	public boolean equals(Object o) {
		if (o instanceof ChatMsg) {
			ChatMsg t = (ChatMsg) o;
			return this.id == t.id;
		}
		return super.equals(o);
	}
}
