package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COLLECT.
 */
public class Collect {

	/** Not-null value. */
	private String cid;
	private long aid;
	private long uid;

	public Collect() {
	}

	public Collect(String cid) {
		this.cid = cid;
	}

	public Collect(String cid, long aid, long uid) {
		this.cid = cid;
		this.aid = aid;
		this.uid = uid;
	}

	/** Not-null value. */
	public String getCid() {
		return cid;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setCid(String cid) {
		this.cid = cid;
	}

	public long getAid() {
		return aid;
	}

	public void setAid(long aid) {
		this.aid = aid;
	}

	public long getUid() {
		return uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	@Override
	public boolean equals(Object o) {
		if (o instanceof Collect) {
			Collect t = (Collect) o;
			return this.cid.equals(t.cid);
		}
		return super.equals(o);
	}
}
