package com.listenBook.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.listenBook.greendao.Baseuser;
import com.listenBook.greendao.OtherUser;
import com.listenBook.greendao.Category;
import com.listenBook.greendao.Media;
import com.listenBook.greendao.Article;
import com.listenBook.greendao.ArticleFeedback;
import com.listenBook.greendao.ArticleChapterInfo;
import com.listenBook.greendao.Recommend;
import com.listenBook.greendao.Rank;
import com.listenBook.greendao.Ads;
import com.listenBook.greendao.Down;
import com.listenBook.greendao.Collect;
import com.listenBook.greendao.ReadingTrack;
import com.listenBook.greendao.Feedback;
import com.listenBook.greendao.ChipFeedback;
import com.listenBook.greendao.ChatMsg;
import com.listenBook.greendao.FreshPush;
import com.listenBook.greendao.MeritTableAdult;
import com.listenBook.greendao.MeritTableChildren;
import com.listenBook.greendao.ChatPeopleInfo;
import com.listenBook.greendao.LessonInfo;
import com.listenBook.greendao.LessonMarksInfo;
import com.listenBook.greendao.ArticleChapterRecode;

import com.listenBook.greendao.BaseuserDao;
import com.listenBook.greendao.OtherUserDao;
import com.listenBook.greendao.CategoryDao;
import com.listenBook.greendao.MediaDao;
import com.listenBook.greendao.ArticleDao;
import com.listenBook.greendao.ArticleFeedbackDao;
import com.listenBook.greendao.ArticleChapterInfoDao;
import com.listenBook.greendao.RecommendDao;
import com.listenBook.greendao.RankDao;
import com.listenBook.greendao.AdsDao;
import com.listenBook.greendao.DownDao;
import com.listenBook.greendao.CollectDao;
import com.listenBook.greendao.ReadingTrackDao;
import com.listenBook.greendao.FeedbackDao;
import com.listenBook.greendao.ChipFeedbackDao;
import com.listenBook.greendao.ChatMsgDao;
import com.listenBook.greendao.FreshPushDao;
import com.listenBook.greendao.MeritTableAdultDao;
import com.listenBook.greendao.MeritTableChildrenDao;
import com.listenBook.greendao.ChatPeopleInfoDao;
import com.listenBook.greendao.LessonInfoDao;
import com.listenBook.greendao.LessonMarksInfoDao;
import com.listenBook.greendao.ArticleChapterRecodeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseuserDaoConfig;
    private final DaoConfig otherUserDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig mediaDaoConfig;
    private final DaoConfig articleDaoConfig;
    private final DaoConfig articleFeedbackDaoConfig;
    private final DaoConfig articleChapterInfoDaoConfig;
    private final DaoConfig recommendDaoConfig;
    private final DaoConfig rankDaoConfig;
    private final DaoConfig adsDaoConfig;
    private final DaoConfig downDaoConfig;
    private final DaoConfig collectDaoConfig;
    private final DaoConfig readingTrackDaoConfig;
    private final DaoConfig feedbackDaoConfig;
    private final DaoConfig chipFeedbackDaoConfig;
    private final DaoConfig chatMsgDaoConfig;
    private final DaoConfig freshPushDaoConfig;
    private final DaoConfig meritTableAdultDaoConfig;
    private final DaoConfig meritTableChildrenDaoConfig;
    private final DaoConfig chatPeopleInfoDaoConfig;
    private final DaoConfig lessonInfoDaoConfig;
    private final DaoConfig lessonMarksInfoDaoConfig;
    private final DaoConfig articleChapterRecodeDaoConfig;

    private final BaseuserDao baseuserDao;
    private final OtherUserDao otherUserDao;
    private final CategoryDao categoryDao;
    private final MediaDao mediaDao;
    private final ArticleDao articleDao;
    private final ArticleFeedbackDao articleFeedbackDao;
    private final ArticleChapterInfoDao articleChapterInfoDao;
    private final RecommendDao recommendDao;
    private final RankDao rankDao;
    private final AdsDao adsDao;
    private final DownDao downDao;
    private final CollectDao collectDao;
    private final ReadingTrackDao readingTrackDao;
    private final FeedbackDao feedbackDao;
    private final ChipFeedbackDao chipFeedbackDao;
    private final ChatMsgDao chatMsgDao;
    private final FreshPushDao freshPushDao;
    private final MeritTableAdultDao meritTableAdultDao;
    private final MeritTableChildrenDao meritTableChildrenDao;
    private final ChatPeopleInfoDao chatPeopleInfoDao;
    private final LessonInfoDao lessonInfoDao;
    private final LessonMarksInfoDao lessonMarksInfoDao;
    private final ArticleChapterRecodeDao articleChapterRecodeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseuserDaoConfig = daoConfigMap.get(BaseuserDao.class).clone();
        baseuserDaoConfig.initIdentityScope(type);

        otherUserDaoConfig = daoConfigMap.get(OtherUserDao.class).clone();
        otherUserDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        mediaDaoConfig = daoConfigMap.get(MediaDao.class).clone();
        mediaDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        articleFeedbackDaoConfig = daoConfigMap.get(ArticleFeedbackDao.class).clone();
        articleFeedbackDaoConfig.initIdentityScope(type);

        articleChapterInfoDaoConfig = daoConfigMap.get(ArticleChapterInfoDao.class).clone();
        articleChapterInfoDaoConfig.initIdentityScope(type);

        recommendDaoConfig = daoConfigMap.get(RecommendDao.class).clone();
        recommendDaoConfig.initIdentityScope(type);

        rankDaoConfig = daoConfigMap.get(RankDao.class).clone();
        rankDaoConfig.initIdentityScope(type);

        adsDaoConfig = daoConfigMap.get(AdsDao.class).clone();
        adsDaoConfig.initIdentityScope(type);

        downDaoConfig = daoConfigMap.get(DownDao.class).clone();
        downDaoConfig.initIdentityScope(type);

        collectDaoConfig = daoConfigMap.get(CollectDao.class).clone();
        collectDaoConfig.initIdentityScope(type);

        readingTrackDaoConfig = daoConfigMap.get(ReadingTrackDao.class).clone();
        readingTrackDaoConfig.initIdentityScope(type);

        feedbackDaoConfig = daoConfigMap.get(FeedbackDao.class).clone();
        feedbackDaoConfig.initIdentityScope(type);

        chipFeedbackDaoConfig = daoConfigMap.get(ChipFeedbackDao.class).clone();
        chipFeedbackDaoConfig.initIdentityScope(type);

        chatMsgDaoConfig = daoConfigMap.get(ChatMsgDao.class).clone();
        chatMsgDaoConfig.initIdentityScope(type);

        freshPushDaoConfig = daoConfigMap.get(FreshPushDao.class).clone();
        freshPushDaoConfig.initIdentityScope(type);

        meritTableAdultDaoConfig = daoConfigMap.get(MeritTableAdultDao.class).clone();
        meritTableAdultDaoConfig.initIdentityScope(type);

        meritTableChildrenDaoConfig = daoConfigMap.get(MeritTableChildrenDao.class).clone();
        meritTableChildrenDaoConfig.initIdentityScope(type);

        chatPeopleInfoDaoConfig = daoConfigMap.get(ChatPeopleInfoDao.class).clone();
        chatPeopleInfoDaoConfig.initIdentityScope(type);

        lessonInfoDaoConfig = daoConfigMap.get(LessonInfoDao.class).clone();
        lessonInfoDaoConfig.initIdentityScope(type);

        lessonMarksInfoDaoConfig = daoConfigMap.get(LessonMarksInfoDao.class).clone();
        lessonMarksInfoDaoConfig.initIdentityScope(type);

        articleChapterRecodeDaoConfig = daoConfigMap.get(ArticleChapterRecodeDao.class).clone();
        articleChapterRecodeDaoConfig.initIdentityScope(type);

        baseuserDao = new BaseuserDao(baseuserDaoConfig, this);
        otherUserDao = new OtherUserDao(otherUserDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        mediaDao = new MediaDao(mediaDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);
        articleFeedbackDao = new ArticleFeedbackDao(articleFeedbackDaoConfig, this);
        articleChapterInfoDao = new ArticleChapterInfoDao(articleChapterInfoDaoConfig, this);
        recommendDao = new RecommendDao(recommendDaoConfig, this);
        rankDao = new RankDao(rankDaoConfig, this);
        adsDao = new AdsDao(adsDaoConfig, this);
        downDao = new DownDao(downDaoConfig, this);
        collectDao = new CollectDao(collectDaoConfig, this);
        readingTrackDao = new ReadingTrackDao(readingTrackDaoConfig, this);
        feedbackDao = new FeedbackDao(feedbackDaoConfig, this);
        chipFeedbackDao = new ChipFeedbackDao(chipFeedbackDaoConfig, this);
        chatMsgDao = new ChatMsgDao(chatMsgDaoConfig, this);
        freshPushDao = new FreshPushDao(freshPushDaoConfig, this);
        meritTableAdultDao = new MeritTableAdultDao(meritTableAdultDaoConfig, this);
        meritTableChildrenDao = new MeritTableChildrenDao(meritTableChildrenDaoConfig, this);
        chatPeopleInfoDao = new ChatPeopleInfoDao(chatPeopleInfoDaoConfig, this);
        lessonInfoDao = new LessonInfoDao(lessonInfoDaoConfig, this);
        lessonMarksInfoDao = new LessonMarksInfoDao(lessonMarksInfoDaoConfig, this);
        articleChapterRecodeDao = new ArticleChapterRecodeDao(articleChapterRecodeDaoConfig, this);

        registerDao(Baseuser.class, baseuserDao);
        registerDao(OtherUser.class, otherUserDao);
        registerDao(Category.class, categoryDao);
        registerDao(Media.class, mediaDao);
        registerDao(Article.class, articleDao);
        registerDao(ArticleFeedback.class, articleFeedbackDao);
        registerDao(ArticleChapterInfo.class, articleChapterInfoDao);
        registerDao(Recommend.class, recommendDao);
        registerDao(Rank.class, rankDao);
        registerDao(Ads.class, adsDao);
        registerDao(Down.class, downDao);
        registerDao(Collect.class, collectDao);
        registerDao(ReadingTrack.class, readingTrackDao);
        registerDao(Feedback.class, feedbackDao);
        registerDao(ChipFeedback.class, chipFeedbackDao);
        registerDao(ChatMsg.class, chatMsgDao);
        registerDao(FreshPush.class, freshPushDao);
        registerDao(MeritTableAdult.class, meritTableAdultDao);
        registerDao(MeritTableChildren.class, meritTableChildrenDao);
        registerDao(ChatPeopleInfo.class, chatPeopleInfoDao);
        registerDao(LessonInfo.class, lessonInfoDao);
        registerDao(LessonMarksInfo.class, lessonMarksInfoDao);
        registerDao(ArticleChapterRecode.class, articleChapterRecodeDao);
    }
    
    public void clear() {
        baseuserDaoConfig.getIdentityScope().clear();
        otherUserDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        mediaDaoConfig.getIdentityScope().clear();
        articleDaoConfig.getIdentityScope().clear();
        articleFeedbackDaoConfig.getIdentityScope().clear();
        articleChapterInfoDaoConfig.getIdentityScope().clear();
        recommendDaoConfig.getIdentityScope().clear();
        rankDaoConfig.getIdentityScope().clear();
        adsDaoConfig.getIdentityScope().clear();
        downDaoConfig.getIdentityScope().clear();
        collectDaoConfig.getIdentityScope().clear();
        readingTrackDaoConfig.getIdentityScope().clear();
        feedbackDaoConfig.getIdentityScope().clear();
        chipFeedbackDaoConfig.getIdentityScope().clear();
        chatMsgDaoConfig.getIdentityScope().clear();
        freshPushDaoConfig.getIdentityScope().clear();
        meritTableAdultDaoConfig.getIdentityScope().clear();
        meritTableChildrenDaoConfig.getIdentityScope().clear();
        chatPeopleInfoDaoConfig.getIdentityScope().clear();
        lessonInfoDaoConfig.getIdentityScope().clear();
        lessonMarksInfoDaoConfig.getIdentityScope().clear();
        articleChapterRecodeDaoConfig.getIdentityScope().clear();
    }

    public BaseuserDao getBaseuserDao() {
        return baseuserDao;
    }

    public OtherUserDao getOtherUserDao() {
        return otherUserDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public MediaDao getMediaDao() {
        return mediaDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public ArticleFeedbackDao getArticleFeedbackDao() {
        return articleFeedbackDao;
    }

    public ArticleChapterInfoDao getArticleChapterInfoDao() {
        return articleChapterInfoDao;
    }

    public RecommendDao getRecommendDao() {
        return recommendDao;
    }

    public RankDao getRankDao() {
        return rankDao;
    }

    public AdsDao getAdsDao() {
        return adsDao;
    }

    public DownDao getDownDao() {
        return downDao;
    }

    public CollectDao getCollectDao() {
        return collectDao;
    }

    public ReadingTrackDao getReadingTrackDao() {
        return readingTrackDao;
    }

    public FeedbackDao getFeedbackDao() {
        return feedbackDao;
    }

    public ChipFeedbackDao getChipFeedbackDao() {
        return chipFeedbackDao;
    }

    public ChatMsgDao getChatMsgDao() {
        return chatMsgDao;
    }

    public FreshPushDao getFreshPushDao() {
        return freshPushDao;
    }

    public MeritTableAdultDao getMeritTableAdultDao() {
        return meritTableAdultDao;
    }

    public MeritTableChildrenDao getMeritTableChildrenDao() {
        return meritTableChildrenDao;
    }

    public ChatPeopleInfoDao getChatPeopleInfoDao() {
        return chatPeopleInfoDao;
    }

    public LessonInfoDao getLessonInfoDao() {
        return lessonInfoDao;
    }

    public LessonMarksInfoDao getLessonMarksInfoDao() {
        return lessonMarksInfoDao;
    }

    public ArticleChapterRecodeDao getArticleChapterRecodeDao() {
        return articleChapterRecodeDao;
    }

}
