package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOWN.
 */
public class Down {

    private long cpId;
    private long dId;
    private long aId;
    private long uid;

    public Down() {
    }

    public Down(long cpId) {
        this.cpId = cpId;
    }

    public Down(long cpId, long dId, long aId, long uid) {
        this.cpId = cpId;
        this.dId = dId;
        this.aId = aId;
        this.uid = uid;
    }

    public long getCpId() {
        return cpId;
    }

    public void setCpId(long cpId) {
        this.cpId = cpId;
    }

    public long getDId() {
        return dId;
    }

    public void setDId(long dId) {
        this.dId = dId;
    }

    public long getAId() {
        return aId;
    }

    public void setAId(long aId) {
        this.aId = aId;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }
    @Override
	public boolean equals(Object o) {
		if (o instanceof Down) {
			Down t = (Down) o;
			return this.cpId == t.cpId;
		}
		return super.equals(o);
	}
}
