package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FEEDBACK.
 */
public class Feedback {

    private long fid;
    private String dateline;
    private String msg;

    public Feedback() {
    }

    public Feedback(long fid) {
        this.fid = fid;
    }

    public Feedback(long fid, String dateline, String msg) {
        this.fid = fid;
        this.dateline = dateline;
        this.msg = msg;
    }

    public long getFid() {
        return fid;
    }

    public void setFid(long fid) {
        this.fid = fid;
    }

    public String getDateline() {
        return dateline;
    }

    public void setDateline(String dateline) {
        this.dateline = dateline;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }
    @Override
	public boolean equals(Object o) {
		if (o instanceof Feedback) {
			Feedback t = (Feedback) o;
			return this.fid == t.fid;
		}
		return super.equals(o);
	}
}
