package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FRESH_PUSH.
 */
public class FreshPush {

    private long aId;
    private long media;
    /** Not-null value. */
    private String aIcon;
    /** Not-null value. */
    private String aName;
    /** Not-null value. */
    private String aAbstract;
    /** Not-null value. */
    private String aAuthor;
    private int chapterNum;

    public FreshPush() {
    }

    public FreshPush(long aId) {
        this.aId = aId;
    }

    public FreshPush(long aId, long media, String aIcon, String aName, String aAbstract, String aAuthor, int chapterNum) {
        this.aId = aId;
        this.media = media;
        this.aIcon = aIcon;
        this.aName = aName;
        this.aAbstract = aAbstract;
        this.aAuthor = aAuthor;
        this.chapterNum = chapterNum;
    }

    public long getAId() {
        return aId;
    }

    public void setAId(long aId) {
        this.aId = aId;
    }

    public long getMedia() {
        return media;
    }

    public void setMedia(long media) {
        this.media = media;
    }

    /** Not-null value. */
    public String getAIcon() {
        return aIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAIcon(String aIcon) {
        this.aIcon = aIcon;
    }

    /** Not-null value. */
    public String getAName() {
        return aName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAName(String aName) {
        this.aName = aName;
    }

    /** Not-null value. */
    public String getAAbstract() {
        return aAbstract;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAAbstract(String aAbstract) {
        this.aAbstract = aAbstract;
    }

    /** Not-null value. */
    public String getAAuthor() {
        return aAuthor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAAuthor(String aAuthor) {
        this.aAuthor = aAuthor;
    }

    public int getChapterNum() {
        return chapterNum;
    }

    public void setChapterNum(int chapterNum) {
        this.chapterNum = chapterNum;
    }

}
