package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LESSON_INFO.
 */
public class LessonInfo {

    private Long id;
    /** Not-null value. */
    private String date;
    private String title;
    private String issue;
    private Integer type;
    private String option;
    private String answer;
    private String user_answer;
    private Integer marks;

    public LessonInfo() {
    }

    public LessonInfo(Long id) {
        this.id = id;
    }

    public LessonInfo(Long id, String date, String title, String issue, Integer type, String option, String answer, String user_answer, Integer marks) {
        this.id = id;
        this.date = date;
        this.title = title;
        this.issue = issue;
        this.type = type;
        this.option = option;
        this.answer = answer;
        this.user_answer = user_answer;
        this.marks = marks;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getIssue() {
        return issue;
    }

    public void setIssue(String issue) {
        this.issue = issue;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getOption() {
        return option;
    }

    public void setOption(String option) {
        this.option = option;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getUser_answer() {
        return user_answer;
    }

    public void setUser_answer(String user_answer) {
        this.user_answer = user_answer;
    }

    public Integer getMarks() {
        return marks;
    }

    public void setMarks(Integer marks) {
        this.marks = marks;
    }

}
