package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LESSON_MARKS_INFO.
 */
public class LessonMarksInfo {

    /** Not-null value. */
    private String date;
    private String chant;
    private Integer marks;
    private Boolean iscomplete;
    private String describe;
    private Integer right_count;

    public LessonMarksInfo() {
    }

    public LessonMarksInfo(String date) {
        this.date = date;
    }

    public LessonMarksInfo(String date, String chant, Integer marks, Boolean iscomplete, String describe, Integer right_count) {
        this.date = date;
        this.chant = chant;
        this.marks = marks;
        this.iscomplete = iscomplete;
        this.describe = describe;
        this.right_count = right_count;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public String getChant() {
        return chant;
    }

    public void setChant(String chant) {
        this.chant = chant;
    }

    public Integer getMarks() {
        return marks;
    }

    public void setMarks(Integer marks) {
        this.marks = marks;
    }

    public Boolean getIscomplete() {
        return iscomplete;
    }

    public void setIscomplete(Boolean iscomplete) {
        this.iscomplete = iscomplete;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public Integer getRight_count() {
        return right_count;
    }

    public void setRight_count(Integer right_count) {
        this.right_count = right_count;
    }

}
