package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MERIT_TABLE_ADULT.
 */
public class MeritTableAdult {

    private Long id;
    private long uid;
    /** Not-null value. */
    private String date;
    private Integer idea=0;
    private Integer attitude=0;
    private Integer action=0;
    private Integer treat=0;
    private Integer work=0;
    private Integer belief=0;
    private Integer other=0;
    private Integer gong=0;
    private Integer guo=0;
    private String ideades;
    private String ideaexc;
    private String attitudedes;
    private String attitudeexc;
    private String actiondes;
    private String actionexc;
    private String treatdes;
    private String treatexc;
    private String workdes;
    private String workexc;
    private String beliefdes;
    private String beliefexc;
    private String otherdes;
    private String otherexc;

    public MeritTableAdult() {
    }

    public MeritTableAdult(Long id) {
        this.id = id;
    }

    public MeritTableAdult(Long id, long uid, String date, Integer idea, Integer attitude, Integer action, Integer treat, Integer work, Integer belief, Integer other, Integer gong, Integer guo, String ideades, String ideaexc, String attitudedes, String attitudeexc, String actiondes, String actionexc, String treatdes, String treatexc, String workdes, String workexc, String beliefdes, String beliefexc, String otherdes, String otherexc) {
        this.id = id;
        this.uid = uid;
        this.date = date;
        this.idea = idea;
        this.attitude = attitude;
        this.action = action;
        this.treat = treat;
        this.work = work;
        this.belief = belief;
        this.other = other;
        this.gong = gong;
        this.guo = guo;
        this.ideades = ideades;
        this.ideaexc = ideaexc;
        this.attitudedes = attitudedes;
        this.attitudeexc = attitudeexc;
        this.actiondes = actiondes;
        this.actionexc = actionexc;
        this.treatdes = treatdes;
        this.treatexc = treatexc;
        this.workdes = workdes;
        this.workexc = workexc;
        this.beliefdes = beliefdes;
        this.beliefexc = beliefexc;
        this.otherdes = otherdes;
        this.otherexc = otherexc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Integer getIdea() {
        return idea;
    }

    public void setIdea(Integer idea) {
        this.idea = idea;
    }

    public Integer getAttitude() {
        return attitude;
    }

    public void setAttitude(Integer attitude) {
        this.attitude = attitude;
    }

    public Integer getAction() {
        return action;
    }

    public void setAction(Integer action) {
        this.action = action;
    }

    public Integer getTreat() {
        return treat;
    }

    public void setTreat(Integer treat) {
        this.treat = treat;
    }

    public Integer getWork() {
        return work;
    }

    public void setWork(Integer work) {
        this.work = work;
    }

    public Integer getBelief() {
        return belief;
    }

    public void setBelief(Integer belief) {
        this.belief = belief;
    }

    public Integer getOther() {
        return other;
    }

    public void setOther(Integer other) {
        this.other = other;
    }

    public Integer getGong() {
        return gong;
    }

    public void setGong(Integer gong) {
        this.gong = gong;
    }

    public Integer getGuo() {
        return guo;
    }

    public void setGuo(Integer guo) {
        this.guo = guo;
    }

    public String getIdeades() {
        return ideades;
    }

    public void setIdeades(String ideades) {
        this.ideades = ideades;
    }

    public String getIdeaexc() {
        return ideaexc;
    }

    public void setIdeaexc(String ideaexc) {
        this.ideaexc = ideaexc;
    }

    public String getAttitudedes() {
        return attitudedes;
    }

    public void setAttitudedes(String attitudedes) {
        this.attitudedes = attitudedes;
    }

    public String getAttitudeexc() {
        return attitudeexc;
    }

    public void setAttitudeexc(String attitudeexc) {
        this.attitudeexc = attitudeexc;
    }

    public String getActiondes() {
        return actiondes;
    }

    public void setActiondes(String actiondes) {
        this.actiondes = actiondes;
    }

    public String getActionexc() {
        return actionexc;
    }

    public void setActionexc(String actionexc) {
        this.actionexc = actionexc;
    }

    public String getTreatdes() {
        return treatdes;
    }

    public void setTreatdes(String treatdes) {
        this.treatdes = treatdes;
    }

    public String getTreatexc() {
        return treatexc;
    }

    public void setTreatexc(String treatexc) {
        this.treatexc = treatexc;
    }

    public String getWorkdes() {
        return workdes;
    }

    public void setWorkdes(String workdes) {
        this.workdes = workdes;
    }

    public String getWorkexc() {
        return workexc;
    }

    public void setWorkexc(String workexc) {
        this.workexc = workexc;
    }

    public String getBeliefdes() {
        return beliefdes;
    }

    public void setBeliefdes(String beliefdes) {
        this.beliefdes = beliefdes;
    }

    public String getBeliefexc() {
        return beliefexc;
    }

    public void setBeliefexc(String beliefexc) {
        this.beliefexc = beliefexc;
    }

    public String getOtherdes() {
        return otherdes;
    }

    public void setOtherdes(String otherdes) {
        this.otherdes = otherdes;
    }

    public String getOtherexc() {
        return otherexc;
    }

    public void setOtherexc(String otherexc) {
        this.otherexc = otherexc;
    }

}
