package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MERIT_TABLE_CHILDREN.
 */
public class MeritTableChildren {

    private Long id;
    private long uid;
    /** Not-null value. */
    private String date;
    private Integer schedules=0;
    private Integer attitude=0;
    private Integer study=0;
    private Integer love=0;
    private Integer respect=0;
    private Integer action=0;
    private Integer other=0;
    private Integer gong=0;
    private Integer guo=0;
    private String schedulesdes;
    private String schedulesexc;
    private String attitudedes;
    private String attitudeexc;
    private String studydes;
    private String studyexc;
    private String lovedes;
    private String loveexc;
    private String respectdes;
    private String respectexc;
    private String actiondes;
    private String actionexc;
    private String otherdes;
    private String otherexc;

    public MeritTableChildren() {
    }

    public MeritTableChildren(Long id) {
        this.id = id;
    }

    public MeritTableChildren(Long id, long uid, String date, Integer schedules, Integer attitude, Integer study, Integer love, Integer respect, Integer action, Integer other, Integer gong, Integer guo, String schedulesdes, String schedulesexc, String attitudedes, String attitudeexc, String studydes, String studyexc, String lovedes, String loveexc, String respectdes, String respectexc, String actiondes, String actionexc, String otherdes, String otherexc) {
        this.id = id;
        this.uid = uid;
        this.date = date;
        this.schedules = schedules;
        this.attitude = attitude;
        this.study = study;
        this.love = love;
        this.respect = respect;
        this.action = action;
        this.other = other;
        this.gong = gong;
        this.guo = guo;
        this.schedulesdes = schedulesdes;
        this.schedulesexc = schedulesexc;
        this.attitudedes = attitudedes;
        this.attitudeexc = attitudeexc;
        this.studydes = studydes;
        this.studyexc = studyexc;
        this.lovedes = lovedes;
        this.loveexc = loveexc;
        this.respectdes = respectdes;
        this.respectexc = respectexc;
        this.actiondes = actiondes;
        this.actionexc = actionexc;
        this.otherdes = otherdes;
        this.otherexc = otherexc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Integer getSchedules() {
        return schedules;
    }

    public void setSchedules(Integer schedules) {
        this.schedules = schedules;
    }

    public Integer getAttitude() {
        return attitude;
    }

    public void setAttitude(Integer attitude) {
        this.attitude = attitude;
    }

    public Integer getStudy() {
        return study;
    }

    public void setStudy(Integer study) {
        this.study = study;
    }

    public Integer getLove() {
        return love;
    }

    public void setLove(Integer love) {
        this.love = love;
    }

    public Integer getRespect() {
        return respect;
    }

    public void setRespect(Integer respect) {
        this.respect = respect;
    }

    public Integer getAction() {
        return action;
    }

    public void setAction(Integer action) {
        this.action = action;
    }

    public Integer getOther() {
        return other;
    }

    public void setOther(Integer other) {
        this.other = other;
    }

    public Integer getGong() {
        return gong;
    }

    public void setGong(Integer gong) {
        this.gong = gong;
    }

    public Integer getGuo() {
        return guo;
    }

    public void setGuo(Integer guo) {
        this.guo = guo;
    }

    public String getSchedulesdes() {
        return schedulesdes;
    }

    public void setSchedulesdes(String schedulesdes) {
        this.schedulesdes = schedulesdes;
    }

    public String getSchedulesexc() {
        return schedulesexc;
    }

    public void setSchedulesexc(String schedulesexc) {
        this.schedulesexc = schedulesexc;
    }

    public String getAttitudedes() {
        return attitudedes;
    }

    public void setAttitudedes(String attitudedes) {
        this.attitudedes = attitudedes;
    }

    public String getAttitudeexc() {
        return attitudeexc;
    }

    public void setAttitudeexc(String attitudeexc) {
        this.attitudeexc = attitudeexc;
    }

    public String getStudydes() {
        return studydes;
    }

    public void setStudydes(String studydes) {
        this.studydes = studydes;
    }

    public String getStudyexc() {
        return studyexc;
    }

    public void setStudyexc(String studyexc) {
        this.studyexc = studyexc;
    }

    public String getLovedes() {
        return lovedes;
    }

    public void setLovedes(String lovedes) {
        this.lovedes = lovedes;
    }

    public String getLoveexc() {
        return loveexc;
    }

    public void setLoveexc(String loveexc) {
        this.loveexc = loveexc;
    }

    public String getRespectdes() {
        return respectdes;
    }

    public void setRespectdes(String respectdes) {
        this.respectdes = respectdes;
    }

    public String getRespectexc() {
        return respectexc;
    }

    public void setRespectexc(String respectexc) {
        this.respectexc = respectexc;
    }

    public String getActiondes() {
        return actiondes;
    }

    public void setActiondes(String actiondes) {
        this.actiondes = actiondes;
    }

    public String getActionexc() {
        return actionexc;
    }

    public void setActionexc(String actionexc) {
        this.actionexc = actionexc;
    }

    public String getOtherdes() {
        return otherdes;
    }

    public void setOtherdes(String otherdes) {
        this.otherdes = otherdes;
    }

    public String getOtherexc() {
        return otherexc;
    }

    public void setOtherexc(String otherexc) {
        this.otherexc = otherexc;
    }

}
