package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OTHER_USER.
 */
public class OtherUser {

	private long uid;
	private String nick;
	private String icon;
	private String sex;
	private String signature;
	private String contact;
	private String area;
	private String phone;
	private String email;
	private Boolean isfriend;
	private Integer friendsCount;
	private Integer collectCount;

	public OtherUser() {
	}

	public OtherUser(long uid) {
		this.uid = uid;
	}

	public OtherUser(long uid, String nick, String icon, String sex,
			String signature, String contact, String area, String phone,
			String email, Boolean isfriend, Integer friendsCount,
			Integer collectCount) {
		this.uid = uid;
		this.nick = nick;
		this.icon = icon;
		this.sex = sex;
		this.signature = signature;
		this.contact = contact;
		this.area = area;
		this.phone = phone;
		this.email = email;
		this.isfriend = isfriend;
		this.friendsCount = friendsCount;
		this.collectCount = collectCount;
	}

	public long getUid() {
		return uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	public String getNick() {
		return nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Boolean getIsfriend() {
		return isfriend;
	}

	public void setIsfriend(Boolean isfriend) {
		this.isfriend = isfriend;
	}

	public Integer getFriendsCount() {
		return friendsCount;
	}

	public void setFriendsCount(Integer friendsCount) {
		this.friendsCount = friendsCount;
	}

	public Integer getCollectCount() {
		return collectCount;
	}

	public void setCollectCount(Integer collectCount) {
		this.collectCount = collectCount;
	}

	@Override
	public boolean equals(Object o) {
		if (o instanceof OtherUser) {
			OtherUser t = (OtherUser) o;
			return this.uid == t.uid;
		}
		return super.equals(o);
	}
}
