package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RANK.
 */
public class Rank {

    private long aId;
    /** Not-null value. */
    private String aIcon;
    /** Not-null value. */
    private String aName;
    /** Not-null value. */
    private String aAbstract;
    /** Not-null value. */
    private String aAuthor;
    private int num;
    private long media;
    /** Not-null value. */
    private String type;
    private Integer rankid;

    public Rank() {
    }

    public Rank(long aId) {
        this.aId = aId;
    }

    public Rank(long aId, String aIcon, String aName, String aAbstract, String aAuthor, int num, long media, String type, Integer rankid) {
        this.aId = aId;
        this.aIcon = aIcon;
        this.aName = aName;
        this.aAbstract = aAbstract;
        this.aAuthor = aAuthor;
        this.num = num;
        this.media = media;
        this.type = type;
        this.rankid = rankid;
    }

    public long getAId() {
        return aId;
    }

    public void setAId(long aId) {
        this.aId = aId;
    }

    /** Not-null value. */
    public String getAIcon() {
        return aIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAIcon(String aIcon) {
        this.aIcon = aIcon;
    }

    /** Not-null value. */
    public String getAName() {
        return aName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAName(String aName) {
        this.aName = aName;
    }

    /** Not-null value. */
    public String getAAbstract() {
        return aAbstract;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAAbstract(String aAbstract) {
        this.aAbstract = aAbstract;
    }

    /** Not-null value. */
    public String getAAuthor() {
        return aAuthor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAAuthor(String aAuthor) {
        this.aAuthor = aAuthor;
    }

    public int getNum() {
        return num;
    }

    public void setNum(int num) {
        this.num = num;
    }

    public long getMedia() {
        return media;
    }

    public void setMedia(long media) {
        this.media = media;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public Integer getRankid() {
        return rankid;
    }

    public void setRankid(Integer rankid) {
        this.rankid = rankid;
    }
    @Override
   	public boolean equals(Object o) {
   		if (o instanceof Rank) {
   			Rank t = (Rank) o;
   			return this.aId == t.aId;
   		}
   		return super.equals(o);
   	}
}
