package com.listenBook.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table READING_TRACK.
 */
public class ReadingTrack {

    private long rid;
    private Long time;
    private Integer pos;

    public ReadingTrack() {
    }

    public ReadingTrack(long rid) {
        this.rid = rid;
    }

    public ReadingTrack(long rid, Long time, Integer pos) {
        this.rid = rid;
        this.time = time;
        this.pos = pos;
    }

    public long getRid() {
        return rid;
    }

    public void setRid(long rid) {
        this.rid = rid;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getPos() {
        return pos;
    }

    public void setPos(Integer pos) {
        this.pos = pos;
    }
    @Override
   	public boolean equals(Object o) {
   		if (o instanceof ReadingTrack) {
   			ReadingTrack t = (ReadingTrack) o;
   			return this.rid == t.rid;
   		}
   		return super.equals(o);
   	}
}
